wandb_version: 1

output_dir:
  desc: null
  value: outputs/GPT-tiny
tokenizer_encoding:
  desc: null
  value: gpt2
model_config:
  desc: null
  value:
    n_embd: 768
    n_head: 12
    n_positions: 1024
    n_layer: 6
device:
  desc: null
  value: auto
batch_size:
  desc: null
  value: 4
seq_len:
  desc: null
  value: 1024
num_warmup_steps:
  desc: null
  value: 10
num_training_steps:
  desc: null
  value: 2000
grad_accumulation_steps:
  desc: null
  value: 1
min_lr:
  desc: null
  value: 0.0001
max_lr:
  desc: null
  value: 0.0005
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701231706.639868
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
